### ISSUE TITLE
Enable customisations of order of wp/activity

### ISSUE THREAD

**Issue by giocomai** [giocomai/ganttrify#12]
Choice could be between alphabetical, and order in which wp/activities provided in input files.

**Comment by krzyklo** [comment]
I was thinking it might be done via additional columns: eg. Sequence, where user could put integer numbers, of how he would like to structure/sequence, and column Bold, where 0 would mean plain, and 1 would be bold, and hence circumvent this customization issues by giving the user ability to tweak manually..

**Comment by giocomai** [comment]
Next time I work on this I will likely integrate it with the `ggtext` package and all such customisations should become much easier.

**Comment by Tuna-92** [comment]
Is is possible to manually choose the order of wp/activities on the y-axis?

**Comment by giocomai** [comment]
The order in which wp/activities first appear is the one that is used. Adding an additional column for reorder is the feature requested here, which I may add, but it should be trivial in most cases to reorder before passing this to ganttrify. 

Make sure you have the latest version, as for a brief time between updates this didn't work as expected. 

``` r
remotes::install_github("giocomai/ganttrify")

library("ganttrify")

project <- tibble::tribble(
  ~wp, ~activity, ~start_date, ~end_date, 
  "b", "bb", 1, 5, 
  "b", "aa", 3, 6,
  "a", "cc", 2, 4, 
  "a", "dd", 5,6
)


ganttrify(
  project = project,
  project_start_date = "2024-04"
)
```

![](https://i.imgur.com/OyjD6mW.png)

<sup>Created on 2024-04-08 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by giocomai** [comment]
Actually, consistently keeping the order of the input is realistically the best default, so I'll close this one, unless someone sees a good reason to have it.

**Comment by Tuna-92** [comment]
Thansk @giocomai update solved my problems
