### ISSUE TITLE
Hide date label from axis of the project

### ISSUE THREAD

**Issue by hasantahir** [giocomai/ganttrify#14]
Hi,

Many thanks for this very helpful package. Is there a way to hide the project starting date from a figure like the one shown at the bottom of the figure below?

![image](https://user-images.githubusercontent.com/11236148/98117444-ae6ed880-1ea1-11eb-8fd7-3a7532859a3d.png)

**Comment by giocomai** [comment]
Just to clarify: do you mean removing only the label for the first month (so, same as above, but without "Nov 2020", and everything as normal from "Dec 2020)), or all the dates on the x-axis, or something else completely?

**Comment by hasantahir** [comment]
Removing all the dates in the format (MMM YYYY) below the chart. The month number above the chart using the argument ```month_number = TRUE,``` does the job for me.

**Comment by giocomai** [comment]
Makes sense. I added a parameter. Update again the package from this repository and the following should work:
``` r
library("ganttrify")
ganttrify(project = ganttrify::test_project,
          month_number_label = TRUE,
          month_date_label = FALSE)
```

![](https://i.imgur.com/KdbwcDe.png)

``` r

# if you prefer month labels on the lower side

ganttrify(project = ganttrify::test_project,
          month_number_label = TRUE,
          month_date_label = FALSE,
          x_axis_position = "bottom")
```

![](https://i.imgur.com/w6916fj.png)

<sup>Created on 2020-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hasantahir** [comment]
Many thanks for addressing this so promptly!

**Comment by adityaa1729** [comment]
Hey!
Many thanks for producing such a useful package! 

As, my query is somewhat related. So thought to post it here.

I want to know if we can switch (interchange) the labels of x-axis i.e, Month number ( month_number_label = TRUE)  can come to the bottom and Date (month_date_label = TRUE) to the top. As, by default Month number comes on top, when day number also exists.

Many thanks in advance, 
A.
