### ISSUE TITLE
start_time

### ISSUE THREAD

**Issue by jibanes** [giocomai/ganttrify#16]
Please see the enclosed picture, what do you think is the reason why start_date is displayed under the chart?
![timechart](https://user-images.githubusercontent.com/1454666/99457792-6491e380-28e0-11eb-9602-f165caa17981.png)

**Comment by giocomai** [comment]
Thanks for pointing this out, it's a regression introduced when fixing a recent issue. 

Also consider that you may want to customise how many years you see on the x-axis, with something like:

```
library("ganttrify")
library("ggplot2")
ganttrify(project = ganttrify::test_project,
          month_number_label = FALSE,
          month_date_label = FALSE) +
  scale_x_date(name = "", breaks = scales::pretty_breaks(n = 10))

```
