### ISSUE TITLE
Extent / change color pallet

### ISSUE THREAD

**Issue by nise** [giocomai/ganttrify#19]
Could you describe how to change the color pallet in use. 

For more then 5 work packages the colors are repeating.

**Comment by giocomai** [comment]
Yes, this is the prupose of the `colour_palette` parameter. You can pass a palette, or simply a character vector with hex of as many colours as you like, e.g. (colours at random):


```
ganttrify(project = ganttrify::test_project,
          colour_palette = c("#6ACCEA",
                             "#00FFB8",
                             "#B90000",
                             "#6C919C",
                             "#94A1A4",
                             "#6ACCEA",
                             "#67AEC3",
                             "#9ACEDE"))

```

**Comment by nise** [comment]
Thanx! I found it finally in the R code. Maybe you could add a list of properties with defaults and example in the readme
