### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Vancamjr** [giocomai/ganttrify#26]
Both remotes & devtools fail returning a 5.1 unexpected input error.
   remotes::install_github("giocomai/ganttrify") and 
   devtools::install_github("giocomai/ganttrify")

Error details from RStudio 2021.09.1 Build 372 using 
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie

Output inset below:
===============================================
> remotes::install_github("giocomai/ganttrify")
Downloading GitHub repo giocomai/ganttrify@HEAD
✓  checking for file ‘/private/var/folders/nd/2zpsrqlj7tbghpf91g560r_m0000gn/T/RtmpOLWPLp/remotes7bc65ef77ad3/giocomai-ganttrify-75427e8/DESCRIPTION’ ...
─  preparing ‘ganttrify’:
✓  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ganttrify_0.0.0.9007.tar.gz’
   
Error: 5:1: unexpected input
5:  
    ^
Execution halted
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/nd/2zpsrqlj7tbghpf91g560r_m0000gn/T//RtmpOLWPLp/file7bc649a0e35a/ganttrify_0.0.0.9007.tar.gz’ had non-zero exit status

===============================================
> devtools::install_github("giocomai/ganttrify")
Downloading GitHub repo giocomai/ganttrify@HEAD
✓  checking for file ‘/private/var/folders/nd/2zpsrqlj7tbghpf91g560r_m0000gn/T/RtmpOLWPLp/remotes7bc67a772a67/giocomai-ganttrify-75427e8/DESCRIPTION’ (357ms)
─  preparing ‘ganttrify’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ganttrify_0.0.0.9007.tar.gz’
   
Error: 5:1: unexpected input
5:  
    ^
Execution halted
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/nd/2zpsrqlj7tbghpf91g560r_m0000gn/T//RtmpOLWPLp/file7bc625810f01/ganttrify_0.0.0.9007.tar.gz’ had non-zero exit status

**Comment by giocomai** [comment]
I cannot reproduce this, not sure what is going on here...
