### ISSUE TITLE
Change Month Labels

### ISSUE THREAD

**Issue by hasantahir** [giocomai/ganttrify#46]
Hi there,

Is there a way to change the month labels on the x-axis from `M1` to `Mo1`? I have milestone spots on the timeline and it would be nice to avoid confusion.

Cheers

**Comment by giocomai** [comment]
You mean, like this?

Update the package and customise the newly introduced  `month_label_string`:

``` r
library("ganttrify")

ganttrify(project = ganttrify::test_project,
          project_start_date = "2024-01",
          font_family = "Roboto Condensed",
          month_label_string = "Mo")
```

![](https://i.imgur.com/672wuQW.png)

<sup>Created on 2024-01-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by hasantahir** [comment]
Awesome, exactly what I was seeking. Thank you.
