### ISSUE TITLE
Ignoring linewidth

### ISSUE THREAD

**Issue by Kath1240** [giocomai/ganttrify#47]
Hi 
First, I love this tool, it makes such good charts.
I have a little problem that when I run it says "Ignoring unknown parameters: linewidth" ,  I have 30 entries and think it could be because of this,  I have tried altering size activity, but would appreciate any advice . 
Thanks in advance :)

**Comment by giocomai** [comment]
hi!

My guess is that this is related to the fact that you have an old version of ggplot2 installed on your system. 

These days, I've been updating the package in preparation of a CRAN submission, and I have adapted the code in line with a new argument name convention introduced by `ggplot2` with [an update in November 2022](https://www.tidyverse.org/blog/2022/11/ggplot2-3-4-0/#hello-linewidth).

In brief, an easy fix would be for you to update ggplot2 (just a basic: `install.packages("ggplot2")` and then restarting your R session should do), and all should work fine.

A second alternative would be installing an older version of `ganttrify`; like, anything older than a week should probably work. 

Finally, I will try to figure out a way to let the code work for those who have an old version of ggplot, but still doesn't throw warnings for those who use a more recent version.

I'll leave this issue open until I find an adequate fix (note to self: [probably described here](https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/))

**Comment by Kath1240** [comment]
Thank you for your response.

**Comment by giocomai** [comment]
Alright, so I added a few lines that check which ggplot2 version you have installed, and deals with it internally. 

If you just update `ganttrify` with `remotes::install_github("giocomai/ganttrify")`, and then restart R, things should work well on your side. 

Please confirm if this is the case or if you still have this issue even after an update.

**Comment by Kath1240** [comment]
Amazing, that works perfectly, thank you so much
Have a lovely Friday :)

**Comment by giocomai** [comment]
cheers!
