### ISSUE TITLE
Is it possible to sort the order that wp and activities appear on the left side?

### ISSUE THREAD

**Issue by mtthwborg** [giocomai/ganttrify#49]
Currently ganttrify sorts by wp in alphabetical order, and activities in the order they are given. This order is maintained even if the order is changed beforehand such as by factor(). Is it possible to change this order?

**Comment by giocomai** [comment]
This is a regression and did not happen in previous versions. Expected behaviour is that they are kept in the order in which they first appear. This will be fixed. 

``` r
library("ganttrify")

project <- tibble::tribble(
  ~wp, ~activity, ~start_date, ~end_date, 
  "b", "bb", 1, 5, 
  "b", "aa", 3, 6,
  "a", "cc", 2, 4, 
  "a", "dd", 5,6
  )


ganttrify(
  project = project,
  project_start_date = "2023-04"
)
```

![](https://i.imgur.com/N9n4JUs.png)

<sup>Created on 2024-03-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by giocomai** [comment]
fixed in the latest version:

``` r
library("ganttrify")

project <- tibble::tribble(
  ~wp, ~activity, ~start_date, ~end_date, 
  "b", "bb", 1, 5, 
  "b", "aa", 3, 6,
  "a", "cc", 2, 4, 
  "a", "dd", 5,6
  )


ganttrify(
  project = project,
  project_start_date = "2024-04"
)
```

![](https://i.imgur.com/tvTTUsw.png)

<sup>Created on 2024-03-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
