### ISSUE TITLE
Customize spacing beween activities

### ISSUE THREAD

**Issue by Jehops** [giocomai/ganttrify#56]
Hello,

Thanks for creating ganttrify!

I was asked to create a Gantt plot for a software release schedule.

![image](https://github.com/user-attachments/assets/8b2011fa-62c9-49d8-8119-156a8f90b0d0)

A request I received was to reduce the vertical space between the point releases (activities) within a major version (wp; not displayed).  In this case, it would be the vertical space between the lines for 13.3, 13.4, 13.5 and 14.1, 14.2, 14.3,..., while keeping the current space between major releases such as 13.5 and 14.1. Do you have any suggestions?

**Comment by giocomai** [comment]
The easiest workaround would be to set the alpha of wp to zero, rather than hide them completely, and then keep all your other customisations... would that work in your case?

``` r
library("ganttrify")

ganttrify(
  project = ganttrify::test_project,
  alpha_wp = 0,
  font_family = "Roboto Condensed"
)
```

![](https://i.imgur.com/UzoB3wL.png)

``` r

ganttrify(
  project = ganttrify::test_project,
  alpha_wp = 0,
  font_family = "Roboto Condensed"
) +
  ggplot2::scale_y_discrete(name = NULL, labels = NULL)
#> Scale for y is already present.
#> Adding another scale for y, which will replace the existing scale.
```

![](https://i.imgur.com/54Px8Ld.png)

<sup>Created on 2024-07-13 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Jehops** [comment]
Thank you.  That works great.  For posterity, here is what I came up with.

```
library("ganttrify")
library("ggplot2")
setwd("/home/jrm/scm/ff/release_gantt")

rs.df <- read.csv("./schedule.csv")
rs.df$activity <- format(rs.df$activity,nsmall=1)
rel.df <- read.csv("./releases.csv",colClasses=rep("character",3))

png("./gantt_rs.png",3000,2000)
ganttrify(project=rs.df,by_date=T,month_number_label=F,size_text_relative=4,
          line_end_wp="butt",x_axis_position="bottom",show_vertical_lines=F,
          month_breaks=3,alpha_wp=0,font_family="Roboto Condensed",
          hide_activities=F,spots=rel.df,spot_border=0,size_activity=10) +
    scale_y_discrete(name=NULL,breaks=NULL,labels=NULL,expand=c(0,2,0.05,0))
dev.off()
```

![image](https://github.com/user-attachments/assets/c06bdb2d-d2a3-47a9-96af-f8be9c3d018d)
