### ISSUE TITLE
Keep Colors from wp, but suppress wp in plot

### ISSUE THREAD

**Issue by Vithar42** [giocomai/ganttrify#8]
I plan to dig into the code to try and make this work at some point.  But I might just be missing it, is it possible to keep the colors as defined by wp, but hid the bar and text for the actual wp rows?

**Comment by giocomai** [comment]
You mean, keeping only the WP lines without any activity within them? Or do you mean it the other way around, keep the activities, but hide the thicker WP line?

I'm afraid none of them is straightforward to achieve, but may well add this next time I work on this.

**Comment by Vithar42** [comment]
I mean to hide both the activities and lines, and only use it for having the sub-activities be color coated.
